<?php
if(!defined('IN_CMS')) exit;
return array (
  'index.php' => '首页模板',
  'other/book.php' => '留言模板',
  'other/label.php' => 'Tags标签',
  'other/search.php' => '站内搜索',
  'other/sitemap.php' => '网站地图',
  'other/tags.php' => '标签详情',
  'content/list.php' => '内容列表',
  'content/list_pic.php' => '内容列表图片模式',
  'content/page.php' => '单页',
  'content/show.php' => '内容详情',
  'include/bread.php' => '面包屑导航',
  'include/foot.php' => '公共底部',
  'include/head.php' => '公共头部',
  'include/right.php' => '公共右侧',
  'include/book/form.php' => '留言提交表单',
  'include/book/list.php' => '留言列表',
  'mobile/index.php' => '手机站首页',
  'mobile/other/book.php' => '留言模板',
  'mobile/other/label.php' => 'Tags模板',
  'mobile/other/search.php' => '站内搜索',
  'mobile/other/sitemap.php' => '网站地图',
  'mobile/other/tags.php' => '标签详情',
  'mobile/include/foot.php' => '公共底部',
  'mobile/include/head.php' => '公共头部',
  'mobile/include/book/form.php' => '留言提交表单',
  'mobile/include/book/list.php' => '留言列表',
  'mobile/content/list.php' => '内容列表',
  'mobile/content/list_pic.php' => '内容列表图片模式',
  'mobile/content/page.php' => '单页',
  'mobile/content/show.php' => '内容详情',
);
?>